
# This Makefile allows (most of) the TIC test program to be compiled with GCC.
#
# The purpose of this is twofold:
#
# - We benefit from GCC's warnings and error checking, that is better than CC65's.
# - We can run tests with the program, and every measurement  will always succeed.
#   It gives us a way to simulate test runs quickly, and the report such a simulated
#   run produces is useful to count the number of tests and measurements performed
#   at the speed of a modern CPU.

CFLAGS = -W -Wall -O3
CPPFLAGS = -DTIC_PLATFORM_GCC

TIC_OBJS = target_gcc_specific_gcc.o      \
           timing_test_measurement_gcc.o  \
           timing_test_routines_gcc.o     \
           tic_cmd_measurement_test_gcc.o \
           tic_cmd_cpu_test_gcc.o         \
           timing_test_memory_gcc.o       \
           tic_main_gcc.o

tic_gcc : $(TIC_OBJS)
	$(CC) $(LDFLAGS) $^ -o $@

%_gcc.o : %.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $< -o $@

clean :
	$(RM) *_gcc.o tic_gcc
